docs(configuration options): document all config options for askui-ui…
askui/askui pull request #10
Opened 2022-06-09 14:35 UTC by thinh-askui

…controller-server (#AS-979)

2022-06-09 15:37 UTC, mlikasam-askui commented on docs/versioned_docs/version-0.1.6/api/06-Configuration/askui-ui-controller-server.md
> +There are different versions of The Askui-UI-Controller-Server.
where can I find them?
  we need a table with different versions and the supported os and arch

2022-06-09 15:41 UTC, mlikasam-askui commented on docs/versioned_docs/version-0.1.6/api/06-Configuration/askui-ui-controller-server.md
> +It is possible to specify a path for your log files. Log files are written to the console per default.
we don't have access to the server console. when the controller is started with the lib

2022-06-09 17:51 UTC, adi-wan-askui commented on docs/docs/api/06-Configuration/askui-ui-controller-server.md
> +# Askui-UI-Controller-Server
I agree with Samir. As we tackle the naming anyway this sprint, let's call it `askui UI Controller` like we discussed in our naming meeting. Make sure to lowercase `askui` (should always be lowercased, no matter where we use it).

2022-06-09 20:56 UTC, adi-wan-askui requested changes

2022-06-09 20:56 UTC, adi-wan-askui commented on docs/docs/api/06-Configuration/askui-ui-controller-server.md
> +## Table of contents
Title Case for headings :)

2022-06-13 06:05 UTC, adi-wan-askui requested changes

2022-06-13 06:05 UTC, adi-wan-askui commented on docs/versioned_docs/version-0.1.6/api/06-Configuration/askui-ui-controller.md
> +The host the askui UI Controller is running on. This websocket server can be connected with the runner protocol.
I would omit the second sentence. I don't think a user would get it as the runner protocol is our own protocol and the use of websocket communication is an implementation detail. The same goes for the port.

2022-06-13 06:05 UTC, adi-wan-askui commented on docs/versioned_docs/version-0.1.6/api/06-Configuration/askui-ui-controller.md
> +    // choosing the second montor
_monitor_

2022-06-13 06:05 UTC, adi-wan-askui commented on docs/versioned_docs/version-0.1.6/api/06-Configuration/askui-ui-controller.md
> +    // start ask ui controller as minimized application
_askui UI Controller_

2022-06-13 06:20 UTC, adi-wan-askui commented on docs/versioned_docs/version-0.1.6/api/06-Configuration/askui-ui-controller.md
> +</table>
Added some info to our releasing docs: https://www.notion.so/askui/Releasing-442ddac471064772bc883f8e3e1dd689

2022-06-13 08:23 UTC, thinh-askui commented on docs/docs/api/07-configuration.md
> +---
The main branch has the 07-configuration.md file. It's probably an old mistake by myself.  I will correct this in this pull request.

2022-06-14 06:30 UTC, thinh-askui commented on docs/versioned_docs/version-0.1.6/api/06-Configuration/askui-ui-controller-server.md
> +second monitor you can change the value to `1` (`2` for your third monitor etc.).
Which chapter did you mean, maybe I overlook something?

2022-06-14 06:38 UTC, mlikasam-askui commented on docs/versioned_docs/version-0.1.6/api/06-Configuration/askui-ui-controller-server.md
> +second monitor you can change the value to `1` (`2` for your third monitor etc.).
I am not sure which chapter, but I thought your first ticket was to document how to select the display. So I thought maybe you can link what you wrote back then.

2022-06-14 08:20 UTC, mlikasam-askui commented
is the documentation of the client not included in this ticket?

2022-06-14 08:20 UTC, adi-wan-askui approved these changes
Good work :)

2022-06-14 08:20 UTC, merged