As 1034 rename  source code UI controller
askui/askui pull request #13
Opened 2022-06-13 13:54 UTC by mlikasam-askui

2022-06-13 19:10 UTC, thinh-askui requested changes

2022-06-13 19:10 UTC, thinh-askui commented on packages/askui-nodejs/src/execution/control-your-ui-client.ts
>    ) => void = ControlYourUiClient.EMPTY_RESOLVE;
Just a question: controlyourui is outdated. Maybe should also rename controlyouruiclient?

2022-06-14 09:23 UTC, thinh-askui approved these changes

2022-06-14 09:33 UTC, adi-wan-askui approved these changes
Good work :)

2022-06-14 12:17 UTC, programminx-askui commented on packages/askui-nodejs/src/execution/client-interface.ts
> +  readonly inferenceApiApiUrl?: string,
inferenceServerUrl

2022-06-14 12:19 UTC, programminx-askui commented on packages/askui-nodejs/src/lib/download-binaries.ts
> +  win32: ['windows', 'askui-ui-controller.exe'],
:white_check_mark:

2022-06-14 12:21 UTC, programminx-askui commented on packages/askui-nodejs/src/execution/askui-inference-api.ts
> +export class InferenceApi {
InferenceClient

2022-06-14 13:45 UTC, mlikasam-askui commented on examples/askui-nodejs-base-example/Readme.md
> +2 - Write your tests with jasmine. Please note, that you have to use alias_name that you defined in step 1 for the askuiUiControllerServerUrl : `http://<alias_name>:6769`
done

2022-06-14 14:42 UTC, programminx-askui commented on docs/docs/general/04-Continuous Integration/askui-ui-controller-docker-images.md
> +let askuiUiControllerServer: UiControlServer;
askuiUiControllerServer --> uiControllerServer

What do you think?

2022-06-14 14:42 UTC, programminx-askui commented on packages/askui-nodejs/src/execution/execution-runtime.ts
> +    private client: AskuiUiControllerClient,
uiControlClient:

2022-06-14 14:42 UTC, programminx-askui commented on packages/askui-nodejs/src/execution/execution-runtime.ts
> +    private api: InferenceClient,
inferenceClient

2022-06-14 14:45 UTC, mlikasam-askui commented on packages/askui-nodejs/src/execution/askui-ui-controller-client.ts
> +  private currentReject: (reason?: unknown) => void = AskuiUiControllerClient.EMPTY_REJECT;
we need to agree on one name.

2022-06-15 09:55 UTC, programminx-askui commented
Hello @askui/maintainers,

we rename agreement:
- AskuiUIControllerServer -rename-> uiController
- askuiUiControlServerUrl --> uiControllerUrl
- AskuiUIControllerClient -rename-> uiControlClient
- ControlUiApi --> InferenceClient
- remove all prefixes askui*
- rename files remove askui

2022-06-15 09:55 UTC, closed without merging