docs: add in-code docs for the get command (#AS-1398)
askui/askui pull request #193
Opened 2022-10-31 09:30 UTC by mlikasam-askui

2022-10-31 10:41 UTC, adi-wan-askui requested changes
There it is! Like :)

2022-10-31 10:41 UTC, adi-wan-askui commented on packages/askui-nodejs/src/execution/dsl.ts
> +   *
Rm empty line

2022-10-31 10:41 UTC, adi-wan-askui commented on packages/askui-nodejs/src/execution/dsl.ts
> +   * const icon = await aui.get().icon().withText('care left').exec();
Can you add an example of what is returned ;)

```suggestion
   * const icon = await aui.get().icon().withText('care left').exec();
   * console.log(icon)
   * // [{ name: 'icon', text: '...', colors: [...], ... }, ...]
```

(add the details to what is logged, maybe a multiline comment would be better)

2022-10-31 10:41 UTC, adi-wan-askui commented on packages/askui-nodejs/src/execution/dsl.ts
> +   * const detectedElements = await aui.getAll().exec()
Same here, example of what is returned

2022-11-07 15:27 UTC, JohannesDienst-askui requested changes

2022-11-07 15:27 UTC, JohannesDienst-askui commented on docs/docs/api/06-Getters/getall.md
> +     xmin: 1128.2720982142857,
Please correct the indentation 😉

2022-11-07 15:27 UTC, JohannesDienst-askui commented on docs/docs/api/06-Getters/getall.md
> +     xmin: 250.8204241071428,
Please correct the indentation 😉

2022-11-08 12:58 UTC, JohannesDienst-askui approved these changes

2022-11-09 08:47 UTC, adi-wan-askui approved these changes

2022-11-09 10:39 UTC, merged