docs: add new android tutorial for web searching automation
askui/askui pull request #223
Opened 2022-11-29 09:48 UTC by HaramChoi-askui

Added a new tutorial for web searching in android devices.

2022-11-30 12:02 UTC, thinh-askui requested changes
Good job! And thank you for helping with the setup :)
I have some remarks but this shouldn't be big changes

2022-11-30 12:02 UTC, thinh-askui commented on docs/docs/general/06-Tutorials/android-search-in-browser.md
> +![annotated-chrome](images/annotation-chrome.png)
Did you use the `annotation.png`? If not you can just delete it

2022-12-02 09:14 UTC, HaramChoi-askui commented
@thinh-askui Thank you for the review. I have applied the points you mentioned. The unused .png has beed deleted. Thanks for that!

2022-12-05 07:11 UTC, thinh-askui approved these changes
Good Job Haram!

2022-12-05 15:12 UTC, merged