feat(dsl): added the reduced class set
askui/askui pull request #236
Opened 2022-12-10 14:39 UTC by programminx-askui

2022-12-12 06:55 UTC, mlikasam-askui requested changes
we need to increase the api version and deprecate the old versions because of the dsl  breaking changes

2022-12-15 14:41 UTC, JohannesDienst-askui requested changes

2022-12-15 14:41 UTC, JohannesDienst-askui commented on docs/docs/api/03-Filters/withtext.md
> +// usually false
adi-wan asked me to remove this comment, so I did.

2022-12-15 14:41 UTC, JohannesDienst-askui commented on docs/docs/api/01-API/table-of-contents.md
> +custom_edit_url: null
Please remove this as it breaks the `Edit this page` button at the bottom of the page.

2022-12-15 14:42 UTC, JohannesDienst-askui commented
Except of the two subtle things I do approve 👍

2022-12-15 14:46 UTC, mlikasam-askui commented on docs/docs/api/03-Filters/icon.md
> +Note: This is an alpha feature. The prediction of the icon name is sometimes unstable. Use custom elements as an alternative.
is there a reason for removing this ?

2022-12-15 15:41 UTC, programminx-askui commented on docs/docs/api/03-Filters/icon.md
> +Note: This is an alpha feature. The prediction of the icon name is sometimes unstable. Use custom elements as an alternative.
Generated.

2022-12-16 09:30 UTC, mlikasam-askui commented
> we need to increase the api version and deprecate the old versions because of the dsl breaking changes and the api doc still need to be updated

no need since the response will be "Could not parse instruction. If you are using an askui product, "
                    "please upgrade to the newest version"

2022-12-16 09:31 UTC, mlikasam-askui approved these changes

2023-03-23 23:29 UTC, closed without merging