Enable model configuration (#CO-277)
askui/askui pull request #358
Opened 2023-03-28 09:23 UTC by mlikasam-askui

* Enable inference configuration through  the ui-controlclient configuration

**Jira**
CO-277

2023-03-30 08:51 UTC, programminx-askui requested changes

2023-03-30 08:51 UTC, programminx-askui commented on packages/askui-nodejs/src/execution/model-composition-branch.ts
> +  tag: string[],
tags*

2023-04-04 15:10 UTC, jhaux-askui requested changes
sorry, wrong PR :sweat_smile:

2023-04-05 07:45 UTC, programminx-askui approved these changes

2023-04-17 18:48 UTC, merged