moved the installation guides into a special folder and renamed them.…
askui/askui pull request #627
Opened 2024-01-30 07:55 UTC by mrmeier-1

… Still need to check the links 😅. Also added a page at the end, called What's Next

2024-02-08 18:07 UTC, programminx-askui requested changes
Hello, 

I've reviewed the the docs and my main findings are:
- Renaming issues
  -  `Askui-*` to `AskUI-*`
  - Renamings from parameters
- Unused Images from the Installer

My question is, how are we proceeding from here?

2024-02-08 18:07 UTC, programminx-askui commented on docs/versioned_docs/version-0.13.1/general/02-Components/AskUI-Development-Environment.md
> +sidebar_position: 3
I don't want to correct twice.

2024-02-09 10:55 UTC, JohannesDienst-askui commented on docs/versioned_docs/version-0.13.1/general/02-Components/AskUI-Development-Environment.md
> +sidebar_position: 3
We have to copy the contents to 0.13.1 so it is the default when users get to the docs.

2024-02-09 11:13 UTC, JohannesDienst-askui commented on docs/sidebars.js
> +  // docsSidebar: [{ type: 'autogenerated', dirName: 'general' }],
No, this is intended as we do need to define the Sidebar manually.

2024-02-09 11:24 UTC, JohannesDienst-askui commented on docs/blog/2024-02-07/2024-02-07.md
> +    - Create a new project by typing **`AskUI-NewProject`**.
Added a note that explains this.

2024-02-13 12:55 UTC, programminx-askui approved these changes

2024-02-13 16:11 UTC, merged