Optimize Vs Integration
askui/askui pull request #696
Opened 2024-02-28 15:46 UTC by mlikasam-askui

- Eliminate the hardcoded askui-shell.cmd file path.
- Retain the option for other terminals to remain enabled, as it should be the user's decision.
- Enable "overrideName" to ensure the terminal title consistently displays as askui-shell.
- Update the icon to a robot and apply a magenta color to match the askui theme.

![image](https://github.com/askui/askui/assets/105347215/c90f9fc7-9105-4e45-9c7a-604b8842ac2b)

2024-02-28 15:54 UTC, JohannesDienst-askui commented
I think @programminx-askui can review this better than me.

Just wanted to say I love cute little stuff like the AskUI-themed Android ❤️ !

Can we also get some ASCII-Art in the shell? 🥳

2024-02-28 16:05 UTC, mlikasam-askui commented
> ASCII-Art in the shell?

![image](https://github.com/askui/askui/assets/105347215/1cae220a-542a-4e76-ad2a-fb68bdbf201e)

2024-02-29 08:58 UTC, programminx-askui requested changes
But I like it. I will test it later.

2024-02-29 08:58 UTC, programminx-askui commented on docs/versioned_docs/version-0.14.0/general/02-Components/AskUI-Development-Environment.md
> -        "JavaScript Debug Terminal": null
When you enable the shells, than you should change the `terminal.integrated.profiles.windows` explaination.

2024-02-29 08:59 UTC, programminx-askui approved these changes

2024-02-29 10:34 UTC, merged